name: binaries

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: binaryen \
          libwebkit2gtk-4.1-dev \
          libgtk-3-dev \
          libayatana-appindicator3-dev

    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2

    - name: Download dependencies
      run: |
        cargo install --git https://github.com/DioxusLabs/dioxus dioxus-cli

    - name: Build artifacts
      run: |
        cargo build -p cli --release
        dioxus bundle --bin ncsu_exam_calendar_desktop --release
