name: cargo-tag

on:
  push:

jobs:
  update-tag:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: jq

    - uses: dtolnay/rust-toolchain@stable

    - id: get-tag
      name: Get tag from cargo toml
      run: |
        echo "VERSION=v\"$(cargo metadata --format-version 1 | jq '.packages.[] | select(.name == \"ncsu_cal_lib\")| .version' | tr -d '\"')\"" >> "$GITHUB_OUTPUT"

    - uses: cardinalby/git-tag-action@master
      env:
        TAG: ${{ steps.get-tag.outputs.VERSION }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
