name: binaries

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  bundle:
    runs-on: ubuntu-latest

    steps:
    - uses: .github/workflows/binaries.yml

    - uses: AButler/upload-release-assets@v2.0
      with:
        files: 'desktop/dist/bundle/{deb/*.deb,appimage/*.AppImage}; target/release/*ncsu_examc'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
