name: release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  bundle:
    runs-on: ubuntu-latest

    steps:
    - uses: dawidd6/action-download-artifact@v2
      with:
        name: x86_64-linux-ncsu_examc ${{ matrix.node-version }}
    - uses: dawidd6/action-download-artifact@v2
      with:
        name: x86_64-mac-ncsu_examc ${{ matrix.node-version }}

    - uses: AButler/upload-release-assets@v2.0
      with:
        files: '*'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
