name: release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux-x86-bin-cli:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2

    - name: Build artifacts
      run: |
        cargo build -p ncsu_exam_calendar_cli --release
        mv target/release/ncsu_exam_calendar_cli x86_64-linux-ncsu_examc

    - uses: actions/upload-artifact@v3
      with: 
        name: x86_64-linux-cli
        path: |
          x86_64-linux-ncsu_examc
        retention-days: 1

  linux-x86-bin-gui:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: binaryen \
          libwebkit2gtk-4.1-dev \
          libgtk-3-dev \
          libayatana-appindicator3-dev

    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2

    - name: Download dependencies
      run: |
        cargo install --git https://github.com/DioxusLabs/dioxus dioxus-cli

    - name: Build artifacts
      run: |
        dx bundle --bin ncsu_exam_calendar_desktop --release

    - uses: actions/upload-artifact@v3
      with: 
        name: x86_64-linux-desktop
        path: |
          desktop/dist/bundle/deb/*.deb
          desktop/dist/bundle/appimage/*.AppImage,
        retention-days: 1


  mac-x86-bin-cli:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2

    - name: Build artifacts
      run: |
        cargo build -p ncsu_exam_calendar_cli --release
        mv target/release/ncsu_exam_calendar_cli x86_64-mac-ncsu_examc

    - uses: actions/upload-artifact@v3
      with: 
        name: x86_64-mac-cli
        path: |
          x86_64-mac-ncsu_examc
        retention-days: 1

  mac-x86-bin-gui:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2

    - name: Download dependencies
      run: |
        brew install binaryen
        cargo install --git https://github.com/DioxusLabs/dioxus dioxus-cli

    - name: Build artifacts
      run: |
        dx bundle --bin ncsu_exam_calendar_desktop --release

    - uses: actions/upload-artifact@v3
      with: 
        name: x86_64-mac-gui
        path: |
          desktop/dist/bundle/macos/*.app
          desktop/dist/bundle/dmg/*.dmg
        retention-days: 1

  windows-x86-bin-cli:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2

    - name: Build artifacts
      run: |
        cargo build -p ncsu_exam_calendar_cli --release
        #move target\release\ncsu_exam_calendar_cli x86-windows-ncsu_examc

    - run: ls target/release/

    - uses: actions/upload-artifact@v3
      with: 
        name: x86_64-windows-cli
        path: |
          x86_64-windows-ncsu_examc
        retention-days: 1

  windows-x86-bin-gui:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2

    - name: Download dependencies
      run: |
        choco install binaryen sed
        cargo install --git https://github.com/DioxusLabs/dioxus dioxus-cli
        sed -i 's;/;\\;g' desktop/Cargo.toml # Filesystem paths...

    - name: Build artifacts
      run: |
        dx bundle --bin ncsu_exam_calendar_desktop --release

    - run: ls desktop/dist/bundle/*

    - uses: actions/upload-artifact@v3
      with: 
        name: x86_64-windows-gui
        path: |
          desktop/dist/bundle/macos/*.app
          desktop/dist/bundle/dmg/*.dmg
        retention-days: 1

  bundle:
    runs-on: ubuntu-latest
    needs: [linux-x86-bin-cli, linux-x86-bin-gui, mac-x86-bin-cli, mac-x86-bin-gui, windows-x86-bin-cli, windows-x86-bin-gui]
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: x86_64-linux-cli
    - uses: actions/download-artifact@v3
      with:
        name: x86_64-linux-gui

    - uses: actions/download-artifact@v3
      with:
        name: x86_64-mac-cli
    - uses: actions/download-artifact@v3
      with:
        name: x86_64-mac-gui

    - uses: actions/download-artifact@v3
      with:
        name: x86_64-windows-cli
    - uses: actions/download-artifact@v3
      with:
        name: x86_64-windows-gui

    - name: Move artifacts to subfolder
      run: |
        shopt -s extglob
        mkdir artifacts
        mv \!(artifacts) artifacts

    - uses: actions/checkout@v4

    - uses: softprops/action-gh-release@v1
      with:
        files: 'artifacts/*'
        generate_release_notes: true
        body_path: CHANGELOG.txt
